### ISSUE TITLE
Error handling could be improved

### ISSUE THREAD

**Issue by huayra** [fgsch/varnish3to4#4]
When translating "error" from 3 to 4 is kind of broken. It works fine as long as you do not something like the URL or the Hostname. I.e. in vcl_recv:
-        error 404 "Not Found";
+        return (synth(404, "Not Found"));

but, this example does not work (req.http.host would not work either):
-        error 751 "http://" + req.url;
+        return (synth(751, "http://")) + req.url;

as we should expect:
+        return (synth(751, "http://" + req.url));

We understand this as a syntax error that can easily be fixed. Would you welcome such an addition?

**Comment by fgsch** [comment]
I thought I fixed this. 😞 

Feel free to submit a PR if it's still happening.

**Comment by huayra** [comment]
PR: https://github.com/fgsch/varnish3to4/pull/7
