### ISSUE TITLE
Purge handling

### ISSUE THREAD

**Issue by huayra** [fgsch/varnish3to4#5]
In Varnish Cache 3.0 you used the keyword “purge” to flush your content.
In Varnish Cache 4.0 the keyword “purge” does not exist, However it’s now possible
to do cache invalidations with purges via VCL as you will see in the example below.

Therefore this does not work anymore:

```
  acl purge {
    "localhost";
    "192.168.55.0"/24;
  }

  sub vcl_recv {
  # allow PURGE from localhost and 192.168.55...

  if (req.request == "PURGE") {
      if (!client.ip ~ purge) {
        error 405 "Not allowed.";
      }
      return (lookup);
    }
  }

  sub vcl_hit {
    if (req.request == "PURGE") {
      purge;
      error 200 "Purged.";
    }
  }

  sub vcl_miss {
    if (req.request == "PURGE") {
      purge;
      error 200 "Purged.";
    }
  }
```
So the example above as in varnish 3, When you called lookup - Varnish tried to
lookup the object in its cache. It will either hit an object or miss it and so
the corresponding subroutine is called.

In vcl_hit the object that is stored in cache is available and the TTL is set.

The `purge` in vcl_miss is necessary to purge all variants in the cases where you
hit an object, but miss a particular variant. This `purge` keyword is retired
from varnish 4 onwards.

So now in order to support purging in Varnish you can simply use this in your VCL:

```
  acl purge {
        "localhost";
        "192.168.55.0"/24;
  }

  sub vcl_recv {
    …
    if (req.method == “PURGE”) {
      return(purge);
    }
  }
```

As you will see above, we have replaced the `purge` keyword with `return(purge)`.
This ends execution of vcl_recv and jumps to vcl_hash. So this is just like
handling a regular request.

When vcl_hash calls return(lookup) varnish will purge the object and then call
`vcl_purge` which removes all variants of an object from cache. There you also 
have the option of adding any particular actions you want Varnish to take once 
it has purge the object, such as doing a `restart`.

Adding basic purge handling would mean to keep the comments that exist in the script right now and add the "if (req.method == "PURGE") { return(purge) ; }" in vcl_recv as per the example above. Would anything else be needed to implement basic purge handling in the script or should that do?

**Comment by fgsch** [comment]
Handling purge is more complicated due to:

1. Using the PURGE verb is a convention but not mandatory.
2. The varnish3to4 script is somewhat limited. 
To be certain you have a purge you also need to scan `vcl_hit{}/vcl_miss{}`.
3. If everything indicates this is a purge, you need to remove the code from `vcl_hit{}/vcl_miss{}` and modify `vcl_recv{}`.

I'm happy to take a look at a patch but I'd also like to keep this relatively simple.

**Comment by huayra** [comment]
I think you have convinced me that trying to do basic purge handling is neither straight forward, nor basic, at least not within the scope of the script.

Let's ponder at this a bit more...

**Comment by fgsch** [comment]
Timed-out.
